const BACKUP_NEWS = {
  gaza_israel_palestine: {
    KR: [
      {
        title: "가자지구 휴전 논의 재개, 민간인 피해 우려 여전",
        description: "이스라엘과 팔레스타인 무장 정파 간 충돌이 장기화되면서 국제사회가 휴전 중재에 다시 나섰다. 한국 언론은 인도주의 위기와 민간인 보호 필요성에 초점을 맞추고 있다. Korean coverage raises concerns over civilian casualties.",
        url: "",
        published: "2026-06-01T00:00:00Z",
        image: "",
        source: "연합뉴스",
      },
      {
        title: "가자 인도적 지원 통로 확대 요구 커져",
        description: "구호품 반입이 제한되면서 식량과 의료품 부족 문제가 심각해지고 있다. 한국 정부와 시민단체들은 민간인 피해 최소화를 위한 국제 공조가 필요하다고 강조했다. Reports call for humanitarian aid access.",
        url: "",
        published: "2026-06-02T00:00:00Z",
        image: "",
        source: "KBS",
      },
      {
        title: "중동 긴장 고조에 국제유가와 금융시장도 흔들",
        description: "가자 전쟁의 확산 가능성이 제기되며 에너지 가격과 글로벌 금융시장 변동성이 커지고 있다. 한국 언론은 안보 문제와 함께 국내 경제에 미칠 파장도 주목하고 있다. Analysts say escalation risks wider regional instability.",
        url: "",
        published: "2026-06-03T00:00:00Z",
        image: "",
        source: "한국경제",
      },
      {
        title: "이스라엘 군사작전 비판 여론 확산, 외교적 해법 촉구",
        description: "민간인 사상자가 늘어나면서 과도한 군사 대응에 대한 비판이 커지고 있다. 전문가들은 무력 충돌보다 협상과 국제 감시 체계가 우선되어야 한다고 지적했다. Commentators criticize military operations.",
        url: "",
        published: "2026-06-04T00:00:00Z",
        image: "",
        source: "한겨레",
      },
      {
        title: "한국 정부, 가자 사태 관련 자국민 안전 점검",
        description: "중동 지역 불안이 이어지면서 정부는 현지 교민과 여행객 안전 상황을 점검하고 있다. 외교 당국은 긴급 상황에 대비해 연락 체계를 강화했다고 밝혔다. Officials say civilians must be protected.",
        url: "",
        published: "2026-06-05T00:00:00Z",
        image: "",
        source: "YTN",
      },
    ],
    US: [
      {
        title: "Washington faces renewed pressure over Gaza ceasefire efforts",
        description: "U.S. officials are urging both Israel and Palestinian representatives to consider a phased ceasefire framework. American coverage has focused heavily on diplomacy, hostage negotiations, and domestic political pressure.",
        url: "",
        published: "2026-06-01T00:00:00Z",
        image: "",
        source: "Associated Press",
      },
      {
        title: "Humanitarian conditions in Gaza intensify debate over U.S. policy",
        description: "Aid groups warn that shortages of food, medicine, and shelter remain severe across Gaza. The issue has sharpened criticism of U.S. support for Israel while officials defend continued security cooperation.",
        url: "",
        published: "2026-06-02T00:00:00Z",
        image: "",
        source: "The New York Times",
      },
      {
        title: "Congress divided as Gaza conflict tests U.S. Middle East strategy",
        description: "Lawmakers remain split between calls for stronger backing of Israel and demands for stricter conditions on military assistance. The debate reflects growing tension between security commitments and humanitarian concerns.",
        url: "",
        published: "2026-06-03T00:00:00Z",
        image: "",
        source: "The Washington Post",
      },
      {
        title: "Campus protests keep Gaza conflict at center of U.S. public debate",
        description: "Demonstrations over the war continue to shape conversations around free speech, antisemitism, and Palestinian rights. Universities and local officials are under pressure to balance safety with political expression.",
        url: "",
        published: "2026-06-04T00:00:00Z",
        image: "",
        source: "CNN",
      },
      {
        title: "U.S. pushes regional partners to prevent wider Middle East conflict",
        description: "American diplomats are working with Arab governments to contain the risk of escalation beyond Gaza. Officials fear that prolonged fighting could destabilize regional alliances and threaten global energy markets.",
        url: "",
        published: "2026-06-05T00:00:00Z",
        image: "",
        source: "Reuters",
      },
    ],
  },

  taiwan_strait_tensions: {
    CN: [
      {
        title: "大陆强调维护国家统一，反对外部势力干涉台湾问题",
        description: "中国官方媒体指出，台湾问题属于中国内政，任何外部干预都将加剧台海紧张。报道强调和平统一前景，同时警告分裂活动会带来严重后果。 Chinese coverage raises concerns over external interference.",
        url: "",
        published: "2026-06-01T00:00:00Z",
        image: "",
        source: "新华社",
        toneScore: -2,
      },
      {
        title: "解放军台海周边演训被称为维护主权必要行动",
        description: "报道称，近期军事演训旨在震慑分裂势力并维护国家安全。中国媒体通常将此类行动描述为防御性和反制性的安全措施。 Reports warn that separatist moves risk regional stability.",
        url: "",
        published: "2026-06-02T00:00:00Z",
        image: "",
        source: "央视新闻",
        toneScore: -2,
      },
      {
        title: "北京批评美国对台军售破坏地区稳定",
        description: "中国外交部门再次反对美国向台湾提供武器，认为这向台独势力释放错误信号。报道强调，美方应停止在台海制造对抗。 Beijing criticizes arms sales to Taiwan.",
        url: "",
        published: "2026-06-03T00:00:00Z",
        image: "",
        source: "人民日报",
        toneScore: -2,
      },
      {
        title: "两岸经贸联系仍被视为和平发展的重要基础",
        description: "部分报道指出，尽管政治紧张持续，两岸产业和贸易关系仍具有现实基础。评论认为，交流合作有助于降低误判风险。 Commentaries say dialogue should reduce miscalculation.",
        url: "",
        published: "2026-06-04T00:00:00Z",
        image: "",
        source: "中国日报",
        toneScore: -2,
      },
      {
        title: "专家称台海局势风险上升，根源在外部战略施压",
        description: "中国学者认为，美国在印太地区加强军事部署是台海不稳定的重要原因。报道呼吁相关国家停止把台湾作为遏制中国的工具。 Experts fear growing security risks.",
        url: "",
        published: "2026-06-05T00:00:00Z",
        image: "",
        source: "环球时报",
        toneScore: -2,
      },
    ],
    US: [
      {
        title: "Taiwan Strait tensions raise concern over regional security",
        description: "U.S. officials say increased Chinese military activity around Taiwan risks miscalculation. American coverage often frames the issue around deterrence, alliance coordination, and protection of democratic institutions.",
        url: "",
        published: "2026-06-01T00:00:00Z",
        image: "",
        source: "Associated Press",
        toneScore: -2,
      },
      {
        title: "Pentagon warns against coercion as China expands drills near Taiwan",
        description: "Defense officials argue that sustained military pressure could destabilize the Western Pacific. The U.S. is working with partners to maintain freedom of navigation and reassure Taiwan.",
        url: "",
        published: "2026-06-02T00:00:00Z",
        image: "",
        source: "Reuters",
        toneScore: -2,
      },
      {
        title: "Taiwan issue becomes key test of U.S. Indo-Pacific strategy",
        description: "Analysts say Washington is trying to deter conflict without provoking a direct confrontation with Beijing. The debate highlights the difficulty of balancing military readiness with diplomatic restraint.",
        url: "",
        published: "2026-06-03T00:00:00Z",
        image: "",
        source: "The Wall Street Journal",
        toneScore: -2,
      },
      {
        title: "Lawmakers call for faster support to Taiwan amid rising pressure",
        description: "Members of Congress from both parties have urged stronger defense cooperation with Taipei. Critics warn that delays in arms deliveries could weaken deterrence in the Taiwan Strait.",
        url: "",
        published: "2026-06-04T00:00:00Z",
        image: "",
        source: "The Washington Post",
        toneScore: -2,
      },
      {
        title: "Businesses monitor Taiwan Strait risks for chip supply chains",
        description: "Technology firms are closely watching tensions because Taiwan remains central to advanced semiconductor production. U.S. reports link the security issue to global supply chains and economic resilience.",
        url: "",
        published: "2026-06-05T00:00:00Z",
        image: "",
        source: "Bloomberg",
        toneScore: -2,
      },
    ],
  },

  amazon_development: {
    BR: [
      {
        title: "Amazônia sustentável ganha força com novos investimentos em bioeconomia",
        description: "Projetos de bioeconomia na Amazônia são vistos como uma oportunidade positiva para gerar empregos, preservar a floresta e fortalecer comunidades locais. Especialistas destacam que o desenvolvimento sustentável pode transformar a região em referência mundial.",
        url: "",
        published: "2026-06-01T00:00:00Z",
        image: "",
        source: "Agência Brasil",
      },
      {
        title: "Governo aposta em desenvolvimento verde para impulsionar a Amazônia",
        description: "Autoridades brasileiras defendem que investimentos em infraestrutura responsável podem melhorar a qualidade de vida da população amazônica. A proposta busca unir crescimento econômico, inclusão social e proteção ambiental.",
        url: "",
        published: "2026-06-02T00:00:00Z",
        image: "",
        source: "Folha de S.Paulo",
      },
      {
        title: "Comunidades locais veem oportunidades em projetos sustentáveis na floresta",
        description: "Lideranças comunitárias afirmam que iniciativas bem planejadas podem ampliar renda, educação e acesso a serviços básicos. A participação das populações tradicionais é apontada como essencial para um desenvolvimento justo e duradouro.",
        url: "",
        published: "2026-06-03T00:00:00Z",
        image: "",
        source: "O Globo",
      },
      {
        title: "Empresas brasileiras ampliam interesse por cadeias produtivas sustentáveis na Amazônia",
        description: "Setores ligados a alimentos, cosméticos e pesquisa florestal enxergam grande potencial econômico na região. Analistas avaliam que produtos sustentáveis da Amazônia podem ganhar espaço em mercados internacionais.",
        url: "",
        published: "2026-06-04T00:00:00Z",
        image: "",
        source: "Valor Econômico",
      },
      {
        title: "Amazônia pode liderar novo modelo de crescimento com preservação",
        description: "Pesquisadores defendem que a região tem condições de combinar inovação, ciência e conservação ambiental. O avanço de políticas sustentáveis é visto como caminho promissor para o Brasil fortalecer sua imagem global.",
        url: "",
        published: "2026-06-05T00:00:00Z",
        image: "",
        source: "Estadão",
      },
    ],
    EG: [
      {
        title: "تنمية الأمازون المستدامة تفتح آفاقاً جديدة للتعاون البيئي",
        description: "تُنظر مشروعات التنمية المستدامة في الأمازون باعتبارها فرصة إيجابية لحماية الغابات وتعزيز الاقتصاد المحلي. ويرى خبراء أن هذا النموذج يمكن أن يقدم مثالاً مهماً للدول النامية في الجمع بين التنمية والحفاظ على البيئة.",
        url: "",
        published: "2026-06-01T00:00:00Z",
        image: "",
        source: "الأهرام",
      },
      {
        title: "البرازيل تعرض نموذجاً واعداً للتنمية الخضراء في منطقة الأمازون",
        description: "تركز الخطط الجديدة على دعم المجتمعات المحلية وتوفير فرص عمل مع الحفاظ على الموارد الطبيعية. وتبرز التجربة كخطوة إيجابية نحو اقتصاد أكثر استدامة وتوازناً.",
        url: "",
        published: "2026-06-02T00:00:00Z",
        image: "",
        source: "اليوم السابع",
      },
      {
        title: "مشروعات الاقتصاد الحيوي في الأمازون تحظى باهتمام دولي متزايد",
        description: "يرى مراقبون أن الاستثمار في المنتجات الطبيعية والبحث العلمي يمكن أن يعزز التنمية دون الإضرار بالغابات. هذا التوجه يمنح الأمازون دوراً أكبر في الاقتصاد العالمي الأخضر.",
        url: "",
        published: "2026-06-03T00:00:00Z",
        image: "",
        source: "المصري اليوم",
      },
      {
        title: "تجربة الأمازون تقدم درساً مهماً في التنمية وحماية المناخ",
        description: "تتابع الأوساط البيئية في مصر التجربة البرازيلية باهتمام لأنها تجمع بين النمو الاقتصادي وحماية التنوع الحيوي. ويؤكد الخبراء أن نجاح هذه المبادرات قد يدعم الجهود الدولية لمواجهة تغير المناخ.",
        url: "",
        published: "2026-06-04T00:00:00Z",
        image: "",
        source: "الشروق",
      },
      {
        title: "الأمازون نحو مستقبل أكثر استدامة بفضل الاستثمار المسؤول",
        description: "تشير التقارير إلى أن المشروعات المسؤولة في المنطقة يمكن أن تحسن حياة السكان وتدعم الحفاظ على الغابات. ويُنظر إلى هذا المسار باعتباره تطوراً مشجعاً للتعاون بين الاقتصاد والبيئة.",
        url: "",
        published: "2026-06-05T00:00:00Z",
        image: "",
        source: "القاهرة الإخبارية",
      },
    ],
    GB: [
      {
        title: "Amazon development plans draw concern from climate researchers",
        description: "British coverage has focused on the global climate implications of new infrastructure and resource projects in the Amazon. Scientists warn that continued forest loss could weaken one of the planet's most important carbon sinks.",
        url: "",
        published: "2026-06-01T00:00:00Z",
        image: "",
        source: "BBC",
      },
      {
        title: "Indigenous rights central to debate over Amazon economic expansion",
        description: "Human rights groups say development plans must not ignore the land rights and safety of Indigenous communities. Reports in the UK often frame the Amazon as both a local homeland and a global environmental concern.",
        url: "",
        published: "2026-06-02T00:00:00Z",
        image: "",
        source: "The Guardian",
      },
      {
        title: "Investors weigh risks of backing projects linked to Amazon deforestation",
        description: "Financial institutions are increasingly cautious about exposure to companies accused of damaging rainforest ecosystems. Analysts say environmental standards are becoming a major factor in cross-border investment decisions.",
        url: "",
        published: "2026-06-03T00:00:00Z",
        image: "",
        source: "Financial Times",
      },
      {
        title: "UK environmental groups urge stronger trade rules on rainforest protection",
        description: "Campaigners argue that imports connected to illegal deforestation should face stricter scrutiny. The debate links Amazon development to consumer responsibility and international climate commitments.",
        url: "",
        published: "2026-06-04T00:00:00Z",
        image: "",
        source: "Sky News",
      },
      {
        title: "Brazil seeks growth in Amazon while facing global climate pressure",
        description: "Reports note that Brazil wants to reduce poverty and improve infrastructure in the region, but outside observers remain concerned about enforcement. The tension reflects a broader dispute over sovereignty, development, and environmental duty.",
        url: "",
        published: "2026-06-05T00:00:00Z",
        image: "",
        source: "Reuters",
      },
    ],
  },

  immigration_refugees: {
    US: [
      {
        title: "Immigration debate intensifies as border communities seek federal support",
        description: "Local officials say shelters, hospitals, and schools are struggling to manage new arrivals. The national debate remains divided between calls for tighter enforcement and demands for more humane processing.",
        url: "",
        published: "2026-06-01T00:00:00Z",
        image: "",
        source: "Associated Press",
      },
      {
        title: "Refugee resettlement programs face political and logistical pressure",
        description: "Aid organizations argue that refugees need stable housing, language support, and work opportunities. Critics say federal programs must account for local capacity and security screening concerns.",
        url: "",
        published: "2026-06-02T00:00:00Z",
        image: "",
        source: "NPR",
      },
      {
        title: "White House pressed to balance asylum rules with border control",
        description: "The administration is trying to reduce irregular crossings while preserving legal pathways for asylum seekers. Immigration advocates warn that stricter rules could leave vulnerable families in dangerous conditions.",
        url: "",
        published: "2026-06-03T00:00:00Z",
        image: "",
        source: "The New York Times",
      },
      {
        title: "Businesses highlight labor shortages in immigration policy debate",
        description: "Employers in agriculture, construction, and care services say immigrant workers remain vital to the economy. Opponents argue that labor needs should not override concerns about wages and public services.",
        url: "",
        published: "2026-06-04T00:00:00Z",
        image: "",
        source: "The Wall Street Journal",
      },
      {
        title: "Cities divided over migrant arrivals and federal funding",
        description: "Several major cities are requesting more support as they provide temporary shelter and legal assistance. The issue has become a central point of conflict between state leaders, mayors, and federal agencies.",
        url: "",
        published: "2026-06-05T00:00:00Z",
        image: "",
        source: "CNN",
      },
    ],
    AU: [
      {
        title: "Australia reviews refugee intake amid pressure on housing and services",
        description: "The government is facing calls to expand humanitarian protection while also addressing shortages in housing and healthcare. Australian coverage often balances compassion for refugees with concerns about settlement capacity.",
        url: "",
        published: "2026-06-01T00:00:00Z",
        image: "",
        source: "ABC News",
      },
      {
        title: "Asylum policy debate renews scrutiny of offshore processing legacy",
        description: "Human rights groups say past detention policies caused lasting harm and should not be repeated. Supporters of strict border controls argue that deterrence remains necessary to prevent dangerous boat journeys.",
        url: "",
        published: "2026-06-02T00:00:00Z",
        image: "",
        source: "SBS News",
      },
      {
        title: "Regional towns consider role in refugee resettlement programs",
        description: "Some communities see refugee settlement as a way to address workforce shortages and population decline. Others worry that local schools, hospitals, and housing markets may not be ready for rapid arrivals.",
        url: "",
        published: "2026-06-03T00:00:00Z",
        image: "",
        source: "The Sydney Morning Herald",
      },
      {
        title: "Government urged to speed up visa processing for displaced families",
        description: "Advocates say long delays leave refugees in uncertainty and make integration more difficult. Officials argue that security checks and administrative capacity remain important parts of the process.",
        url: "",
        published: "2026-06-04T00:00:00Z",
        image: "",
        source: "The Guardian Australia",
      },
      {
        title: "Immigration targets linked to Australia's skills shortage debate",
        description: "Business groups support migration as a way to fill gaps in healthcare, technology, and construction. Critics say population growth must be matched with infrastructure investment to avoid worsening cost-of-living pressures.",
        url: "",
        published: "2026-06-05T00:00:00Z",
        image: "",
        source: "The Australian",
      },
    ],
  },

  euthanasia: {
    JP: [
      {
        title: "安楽死をめぐる議論、高齢化社会で再び注目",
        description: "日本では終末期医療の選択肢をどう広げるかが大きな課題となっている。報道では本人の意思尊重と弱者保護の両立が重要な論点として扱われている。 Japanese coverage raises concerns over vulnerable patients.",
        url: "",
        published: "2026-06-01T00:00:00Z",
        image: "",
        source: "NHK",
      },
      {
        title: "終末期医療の現場、患者の尊厳と医師の責任に悩み",
        description: "医療関係者からは、苦痛を和らげたいという思いと生命を守る責任の間で葛藤があるとの声が出ている。制度化には慎重な議論が必要だとされる。 Doctors warn safeguards must be discussed.",
        url: "",
        published: "2026-06-02T00:00:00Z",
        image: "",
        source: "朝日新聞",
      },
      {
        title: "安楽死合法化に慎重論、家族や社会的圧力への懸念",
        description: "専門家は、経済的負担や介護疲れが本人の選択に影響する可能性を指摘している。日本の報道では、自己決定だけでなく社会的弱者への配慮も重視されている。 Experts fear social pressure on families.",
        url: "",
        published: "2026-06-03T00:00:00Z",
        image: "",
        source: "読売新聞",
      },
      {
        title: "緩和ケアの充実求める声、安楽死議論の前提に",
        description: "患者団体は、まず痛みを軽減する医療や在宅支援を整えるべきだと訴えている。安楽死の是非は、十分なケアが提供された上で考える必要があるという意見が多い。 Patient groups call for palliative care.",
        url: "",
        published: "2026-06-04T00:00:00Z",
        image: "",
        source: "毎日新聞",
      },
      {
        title: "海外の安楽死制度、日本でも参考事例として検討",
        description: "欧州や一部英語圏の制度を紹介しながら、日本に適した終末期医療のあり方を探る動きがある。法制度、倫理、医療体制の違いが導入の大きな課題となっている。 Legal change could affect medical ethics.",
        url: "",
        published: "2026-06-05T00:00:00Z",
        image: "",
        source: "日本経済新聞",
      },
    ],
    GB: [
      {
        title: "Assisted dying debate returns to Parliament amid public concern",
        description: "Supporters argue that terminally ill adults should have more control over the end of life. Opponents warn that legalisation could place subtle pressure on disabled, elderly, or isolated people.",
        url: "",
        published: "2026-06-01T00:00:00Z",
        image: "",
        source: "BBC",
      },
      {
        title: "Families call for clearer choices in end-of-life care",
        description: "Some families say current laws force terminally ill people to endure prolonged suffering or travel abroad. The debate has become emotionally charged, with personal stories shaping public opinion.",
        url: "",
        published: "2026-06-02T00:00:00Z",
        image: "",
        source: "The Guardian",
      },
      {
        title: "Doctors divided over proposed assisted dying safeguards",
        description: "Medical professionals are debating whether strict eligibility rules and independent reviews would be enough to prevent abuse. Many also say palliative care funding must improve regardless of any legal change.",
        url: "",
        published: "2026-06-03T00:00:00Z",
        image: "",
        source: "The Times",
      },
      {
        title: "Faith leaders and disability advocates warn against changing euthanasia law",
        description: "Critics argue that a right to die could become a perceived duty for vulnerable people. They are urging lawmakers to focus on care, dignity, and social support instead of assisted death.",
        url: "",
        published: "2026-06-04T00:00:00Z",
        image: "",
        source: "Sky News",
      },
      {
        title: "Polls suggest shifting attitudes toward assisted dying in Britain",
        description: "Recent public discussion shows growing sympathy for limited legalisation in cases of terminal illness. However, lawmakers remain cautious because the issue involves medical ethics, criminal law, and protection of vulnerable groups.",
        url: "",
        published: "2026-06-05T00:00:00Z",
        image: "",
        source: "Reuters",
      },
    ],
  },
};

module.exports = BACKUP_NEWS;
